### PR TITLE
🐛 Defending against null location 🐛

### LINKED ISSUE #1845: Defect - PostFilter.jsx
I believe this is related to #1843 

Exception when country is null

```
  getAllDomesticCodes(props = this.props) {
    return props.item.data.slice().filter(b => b.location.country === 'United States');
  }

  getAllOverseasCodes(props = this.props) {
    return props.item.data.slice().filter(b => b.location.country !== 'United States');
  }
```

### PR DESCRIPTION
**Pull request by burgwyn**
Closes #1845

### CODE REVIEW

File: src/Components/SearchFilters/PostFilter/PostFilter.jsx [hunk 1]
```diff
@@ -60,11 +60,11 @@ class PostFilter extends Component {
   }
 
   getAllDomesticCodes(props = this.props) {
-    return props.item.data.slice().filter(b => b.location.country === 'United States');
+    return props.item.data.slice().filter(b => (b.location && b.location.country && b.location.country === 'United States'));
```
Comment (mjoyce91) [inline src/Components/SearchFilters/PostFilter/PostFilter.jsx]: The `&& b.location.country` shouldn't be needed since that's already evaluated at the end, but this works.
